### ISSUE TITLE
header.css

### ISSUE THREAD

**Issue by sn0wgit** [aaapa/clinic-plus#3]
Твой хедер выглядит иначе от макета. Что-то мне подсказывает, что его всё-же надо сделать по макету и в таком случае предлагаю для него следующие правки:
```CSS
.header__socials-link {
    /*...*/
    color: #2770f1;
    /*...*/
}

@media (hover: hover) {
    /*...*/
    
    .header__socials-link:hover {
        /*...*/
        color: #ffffff;
    }
    
    /*...*/
}
```
